version: '2.2'

services:
     clickhouse_cyg:
       build: .
       restart: 'no'
       volumes:
         - /home/timofey/feat-extr/snad_clf_features:/data
       user: "1015:1015"
       cpus: 28
       environment:
         - RUST_BACKTRACE=1


    
#networks:
#  clickhouse:
#    external: true
